# Generated by Django 4.2.5 on 2023-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=255)),
                ('ilce', models.CharField(max_length=255)),
                ('mevki', models.CharField(max_length=255)),
                ('fiyat', models.CharField(default='1', max_length=255)),
            ],
        ),
    ]
