# Generated by Django 4.2.5 on 2023-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
