# Generated by Django 4.2.5 on 2024-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satistakipmodel',
            name='indirim_orani',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
