# Generated by Django 4.2.5 on 2023-12-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='manu_name',
            new_name='menu_name',
        ),
    ]
