# Generated by Django 4.2.5 on 2023-09-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
